{"trial_id": "13", "hyperparameters": {"space": [{"class_name": "Int", "config": {"name": "units1", "default": null, "conditions": [], "min_value": 16, "max_value": 144, "step": 16, "sampling": "linear"}}, {"class_name": "Boolean", "config": {"name": "dropout", "default": false, "conditions": []}}, {"class_name": "Int", "config": {"name": "units2", "default": null, "conditions": [], "min_value": 16, "max_value": 144, "step": 16, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units3", "default": null, "conditions": [], "min_value": 16, "max_value": 144, "step": 16, "sampling": "linear"}}, {"class_name": "Float", "config": {"name": "dropout1", "default": 0.0, "conditions": [], "min_value": 0.0, "max_value": 0.3, "step": 0.05, "sampling": "linear"}}, {"class_name": "Boolean", "config": {"name": "dropout2", "default": false, "conditions": []}}, {"class_name": "Boolean", "config": {"name": "dropout3", "default": false, "conditions": []}}], "values": {"units1": 16, "dropout": true, "units2": 16, "units3": 16, "dropout1": 0.2, "dropout2": true, "dropout3": false}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"c:\\Users\\limfy\\anaconda3\\Lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"c:\\Users\\limfy\\anaconda3\\Lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"c:\\Users\\limfy\\anaconda3\\Lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"c:\\Users\\limfy\\anaconda3\\Lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"c:\\Users\\limfy\\anaconda3\\Lib\\site-packages\\keras_tuner\\src\\engine\\hypermodel.py\", line 149, in fit\n    return model.fit(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"c:\\Users\\limfy\\anaconda3\\Lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"C:\\Users\\limfy\\AppData\\Local\\Temp\\__autograph_generated_filelyrte4bj.py\", line 18, in tf__train_function\n    raise\nValueError: in user code:\n\n    File \"c:\\Users\\limfy\\anaconda3\\Lib\\site-packages\\keras\\src\\engine\\training.py\", line 1338, in train_function  *\n        return step_function(self, iterator)\n    File \"c:\\Users\\limfy\\anaconda3\\Lib\\site-packages\\keras\\src\\engine\\training.py\", line 1322, in step_function  **\n        outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"c:\\Users\\limfy\\anaconda3\\Lib\\site-packages\\keras\\src\\engine\\training.py\", line 1303, in run_step  **\n        outputs = model.train_step(data)\n    File \"c:\\Users\\limfy\\anaconda3\\Lib\\site-packages\\keras\\src\\engine\\training.py\", line 1080, in train_step\n        y_pred = self(x, training=True)\n    File \"c:\\Users\\limfy\\anaconda3\\Lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 70, in error_handler\n        raise e.with_traceback(filtered_tb) from None\n\n    ValueError: Exception encountered when calling layer 'dropout_1' (type Dropout).\n    \n    `rate` must be a scalar tensor or a float in the range [0, 1). Received: rate=True\n    \n    Call arguments received by layer 'dropout_1' (type Dropout):\n      \u2022 inputs=tf.Tensor(shape=(None, 1, 16), dtype=float32)\n      \u2022 training=True\n\n"}